name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install aria2 and unzip
      uses: crazy-max/ghaction-chocolatey@v3
      with:
        args: install aria2 unzip -y
    
    - name: Set up Android NDK r23b
      run: | 
        aria2c -o android-ndk-r23b-windows.zip https://dl.google.com/android/repository/android-ndk-r23b-windows.zip
        unzip -q android-ndk-r23b-windows.zip
        cd android-ndk-r23b
        .\prebuilt\windows-x86_64\bin\python.exe .\build\tools\make_standalone_toolchain.py --arch x86_64 --install-dir standalone
      shell: pwsh
      
    - name: Build
      run: |
        android-ndk-r23b/standalone/bin/clang++ -Wall -Werror -nostdlib -c -O3 -o handle.o main.cpp
        android-ndk-r23b/standalone/bin/clang -DMyRelease -Wall -Werror -L ./rootfs/system/lib64 -landroidappmusic -lstoreservicescore -lmediaplatform -lc++_shared -O3 -Wall -o rootfs/system/bin/main handle.o test.c
        android-ndk-r23b/standalone/bin/clang -O3 -Wall -o wrapper wrapper.c
      shell: pwsh
